# Generated by Django 4.2.7 on 2023-12-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_remove_games_max_events_chattext_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='games',
            name='hunger',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='games',
            name='thirst',
            field=models.IntegerField(default=100),
        ),
    ]
